services:
  frontend:
    image: ghcr.io/hvsniddin/textile-front:${IMAGE_TAG:-latest}
    restart: unless-stopped
    ports:
      - "127.0.0.1:5173:80"
    env_file:
      - .env

  api:
    image: ghcr.io/hvsniddin/textile-api:${IMAGE_TAG:-latest}
    restart: unless-stopped
    ports:
      - "127.0.0.1:8000:8000"
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  bot:
    image: ghcr.io/hvsniddin/textile-tgbot:${IMAGE_TAG:-latest}
    restart: unless-stopped
    ports:
      - "127.0.0.1:8080:8080"
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

#  celery-worker:
#    image: ghcr.io/hvsniddin/textile-api:${IMAGE_TAG:-latest}
#    restart: unless-stopped
#    command: celery -A config worker --loglevel=INFO
#    env_file:
#      - .env
#    depends_on:
#      postgres:
#        condition: service_healthy
#      redis:
#        condition: service_healthy
#
#  celery-beat:
#    image: ghcr.io/hvsniddin/textile-api:${IMAGE_TAG:-latest}
#    restart: unless-stopped
#    command: celery -A config beat --loglevel=INFO
#    env_file:
#      - .env
#    depends_on:
#      postgres:
#        condition: service_healthy
#      redis:
#        condition: service_healthy

  postgres:
    image: postgres:17-alpine
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  redis_data:
